// src/App.tsx
import React from "react";
import { Routes, Route } from "react-router-dom";

import { Home, PokemonDetail, Favorites } from "./pages";
import { Header } from "./components";

import "./App.css";

function App() {
  return (
    <div className="App">
      <Header />
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="pokemon/:name" element={<PokemonDetail />} />
        <Route path="/favorites" element={<Favorites />} />
      </Routes>
    </div>
  );
}

export default App;

// solid/src/App.tsx
import { lazy } from "solid-js";
import { useRoutes } from "@solidjs/router";

import styles from "./App.module.css";
import { Header } from "./components";

const routes = [
  {
    path: "/",
    component: lazy(() => import("./pages/Home")),
  },
  {
    path: "/pokemon/:name",
    component: lazy(() => import("./pages/PokemonDetails")),
  },
  {
    path: "/favorites",
    component: lazy(() => import("./pages/Favorites")),
  },
];

function App() {
  const Routes = useRoutes(routes);
  return (
    <>
      <Header />
      <div class={styles.App}>
        <Routes />
      </div>
    </>
  );
}

export default App;
